# Generated by Django 5.2.2 on 2025-06-23 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='commission_value',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Product value (PV) at time of order', max_digits=10),
        ),
    ]
