# Generated by Django 5.2.2 on 2025-06-24 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_orders', '0003_order_payment_proof_alter_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('', 'Select Payment Method'), ('MTN_MOBILE_MONEY', 'MTN Mobile Money'), ('AIRTEL_MONEY', 'Airtel Money'), ('CARD', 'Card'), ('CASH', 'Cash')], default='', max_length=50, null=True),
        ),
    ]
