# Generated by Django 5.2.2 on 2025-06-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_orders', '0004_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='card_expiry',
            field=models.CharField(blank=True, help_text='Credit card expiry date (MM/YY)', max_length=5),
        ),
        migrations.AddField(
            model_name='order',
            name='card_name',
            field=models.CharField(blank=True, help_text='Name on credit card', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='card_number',
            field=models.CharField(blank=True, help_text='Credit card number (last 4 digits only)', max_length=19),
        ),
    ]
