# Generated by Django 5.2.2 on 2025-06-27 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_orders', '0002_alter_order_mlm_processed'),
        ('shop_orders', '0006_alter_orderitem_product_value'),
    ]

    operations = [
    ]
