# Generated by Django 5.2.2 on 2025-06-24 12:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(choices=[('RWF', 'Rwandan Franc'), ('BIF', 'Burundian Franc'), ('KES', 'Kenyan Shilling'), ('UGX', 'Ugandan Shilling'), ('CDF', 'Congolese Franc'), ('TZS', 'Tanzanian Shilling'), ('USD', 'US Dollar')], max_length=3, unique=True)),
                ('exchange_rate', models.DecimalField(decimal_places=4, help_text='Exchange rate from USD (1 USD = X local currency)', max_digits=12)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
