# Generated by Django 5.2.2 on 2025-06-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, choices=[('RW', 'Rwanda (RWF)'), ('BI', 'Burundi (BIF)'), ('KE', 'Kenya (KES)'), ('UG', 'Uganda (UGX)'), ('CD', 'DR Congo (CDF)'), ('TZ', 'Tanzania (TZS)')], max_length=2, null=True),
        ),
    ]
