# Generated by Django 5.2.2 on 2025-06-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_accounts', '0004_add_default_values'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='group_sales_volume',
        ),
        migrations.RemoveField(
            model_name='user',
            name='leadership_bonus_earnings',
        ),
        migrations.RemoveField(
            model_name='user',
            name='matching_bonus_earnings',
        ),
        migrations.RemoveField(
            model_name='user',
            name='personal_sales_volume',
        ),
        migrations.RemoveField(
            model_name='user',
            name='referral_earnings',
        ),
        migrations.RemoveField(
            model_name='user',
            name='retail_bonus_earnings',
        ),
    ]
