# Generated by Django 5.2.2 on 2025-06-23 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='commission_value',
            new_name='product_value',
        ),
    ]
