# Generated by Django 5.2.2 on 2025-06-24 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products', '0002_rename_commission_value_product_product_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_value',
            field=models.DecimalField(decimal_places=2, help_text='PV (Product Value) points for MLM rank advancement', max_digits=10),
        ),
    ]
